package org.egov.inbox.util;

public class TLConstants {
    public static final String TL = "tl-services";
    public static final String MOBILE_NUMBER_PARAM = "mobileNumber";
    public static final String BUSINESS_SERVICE_PARAM = "businessservice";
    public static final String TENANT_ID_PARAM = "tenantId";
    public static final String LOCALITY_PARAM = "locality";
    public static final String ASSIGNEE_PARAM = "assignee";
    public static final String STATUS_PARAM = "status";
    public static final String OFFSET_PARAM = "offset";
    public static final String NO_OF_RECORDS_PARAM = "noOfRecords";
    public static final String LIMIT_PARAM = "limit";
    public static final String REQUESTINFO_PARAM = "RequestInfo";
    public static final String SEARCH_CRITERIA_PARAM = "searchCriteria";
    public static final String USERID_PARAM = "userid";
    public static final String LICENSE_NUMBER_PARAM = "licenseNumber";
    public static final String APPLICATION_NUMBER_PARAM = "applicationNumber";
    public static final String SORT_ORDER_PARAM = "sortOrder";
    public static final String DESC_PARAM = "DESC";
    public static final String FSM_VEHICLE_TRIP_MODULE = "FSM_VEHICLE_TRIP";
    public static final String FSM_MODULE = "FSM";
	public static final String WAITING_FOR_DISPOSAL_STATE = "WAITING_FOR_DISPOSAL";
	public static final String DSO_INPROGRESS_STATE = "DSO_INPROGRESS";
	public static final String CITIZEN_FEEDBACK_PENDING_STATE = "CITIZEN_FEEDBACK_PENDING";
	public static final String DISPOSED_STATE = "DISPOSED";
	public static final String APPLICATIONSTATUS = "applicationstatus";
	public static final String COUNT = "count";
	public static final String STATUSID = "statusid";
	public static final String BUSINESSSERVICE_EXTENSIONOFCLUPERMISSION = "EXTENTION_OF_CLU_PERMISSION";
	public static final String BUSINESSSERVICE_SURRENDOFLICENSE = "SURREND_OF_LICENSE";
	public static final String BUSINESSSERVICE_CHANGEBENEFICIAL = "CHANGE_OF_BENEFICIAL";
	public static final String BUSINESSSERVICE_COMPLETION_CERTIFICATE = "COMPLETION_CERTIFICATE";
	public static final String BUSINESSSERVICE_CONSTRUCTION_OF_COMMUNITY = "CONSTRUCTION_OF_COMMUNITY";
	public static final String BUSINESSSERVICE_TRANSFER = "TRANSFER_OF_LICIENCE";
	public static final String BUSINESSSERVICE_RENEWAL = "RENWAL_OF_LICENCE";
	public static final String BUSINESSSERVICE_REVISED = "REVISED_LAYOUT_PLAN";
	public static final String BUSINESSSERVICE_NEWTL = "NewTL";
	public static final String BUSINESSSERVICE_BG_NEW = "BG_NEW";
	public static final String BUSINESSSERVICE_BG_MORTGAGE = "BG_MORTGAGE";
	public static final String BUSINESSSERVICE_BG_RELEASE = "BG_RELEASE";
	public static final String BUSINESSSERVICE_SERVICE_PLAN = "SERVICE_PLAN";
	public static final String BUSINESSSERVICE_ELECTRICAL_PLAN = "ELECTRICAL_PLAN";
	public static final String BUSINESSSERVICE_SERVICE_PLAN_DEMACATION = "SERVICE_PLAN_DEMARCATION";
	public static final String BUSINESSSERVICE_APPROVAL_OF_STANDARD = "APPROVAL_OF_STANDARD";
	public static final String BUSINESSSERVICE_TECHNICAL_PROFESSIONAL = "TECHNICAL_PROFESSIONAL";
}
